#ifndef DEFAULTS_BONUS_H
# define DEFAULTS_BONUS_H

# define DISPLAY_DEFAULT_W	100
# define DISPLAY_DEFAULT_H	100
# define DISPLAY_MULTIPLIER	10
# define CAM_DEFAULT_CAMUP_X	0
# define CAM_DEFAULT_CAMUP_Y	1
# define CAM_DEFAULT_CAMUP_Z	0
# define CAM_DEFAULT_FOCALLEN	10
# define RENDERER_MAX_DEPTH			10
# define RENDERER_N_SAMPLES			1000
# define RENDERER_UPDATE_FREQ_SHOW	100
# define RENDERER_UPDATE_FREQ_SAVE	1

#endif
